---
title: "Lobby commands"
---

## Logging in and cookies

There are two ways of login in.

## Login with credential

The first way, and the way that must be successfully completed first, is with credentials (username and password). When sending the following (where this particular user is called `Username` and the password for that user is `Password`), you will receive a `login_success` message, if successful and a `login_fail`, if unsuccessful.

```python
# Sent to webtiles: 
{"msg": "login", "username": "Username", "password": "Password"}

# Received if successful:
{"username": "Username", "admin": false, "msg": "login_success"}

# Received if failed:
{"msg": "login_fail"}
```

## Login with cookie

The second way is to log in with a [cookie](https://en.wikipedia.org/wiki/HTTP_cookie). Once you log on successfully with credentials, you can request a cookie from DCSS webtile in the following way: 

```python

# Sent to webtiles
{"msg": "set_login_cookie"}

# Received
{"cookie": "Username%20123075677009872810135587785129954954508", "expires": 7, "msg": "login_cookie"}

```

Once you have a cookie, you can send it back to log on the next time (you will receive a login_success). A new login cookie must be requested every time you use the cookie or once it expires.

```python

# Sent to webtiles:
{"msg": "token_login", "cookie": "Username%20123075677009872810135587785129954954508"}

# Received (if the cookie was good)
{"username": "Username", "admin": false, "msg": "login_success"}

# Received (if the cookie was bad)

{"msg": "login_fail"}
```
